### ISSUE TITLE
Can't download from Eclipse Marketplace using 2024-03 (4.31.0)

### ISSUE THREAD

**Issue by lonvarscsak** [count-negative/qwickie#11]
The following solutions are not available: qwickie 1.2.0 (id=org.eclipse.wst.web_ui.feature.feature.group, site=https://raw.githubusercontent.com/count-negative/qwickie/master/qwickie.updatesite/site.xml)

Any solutions?

**Comment by martinstrejc** [comment]
Hi, I'm facing the same issues, looks like a broken dependency or missing a file or file descriptor. Even though I fixed that localy the plugin didn't work well comparing to previous versions of plugin and Eclipse. Now making a for and let's see if I can fix it in reasonable time I can dedicate to that ;)

**Comment by count-negative** [comment]
please try again with version 1.3.0
